### ISSUE TITLE
ios - MRZ files

### ISSUE THREAD

**Issue by tgreco** [tony-xlh/vision-camera-dynamsoft-label-recognizer#1]
Testing this on iOS I can never get the label recognizer to fire off when scanning passports.
Have you tested this on iOS? 

With the ios MRZ files, how do you make sure it's using that correctly?

**Comment by xulihang** [comment]
It should work on iOS. You can check out this blog for details: https://www.dynamsoft.com/codepool/react-native-mrz-scanner-vision-camera.html

**Comment by CodingWithNobody** [comment]
Check this https://www.youtube.com/watch?v=kOYP2Xun_6o&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=77

**Comment by tony-xlh** [comment]
I've updated the plugin to add the `useCustomModel` method in v0.5.0. It will return false if it cannot load the model files.
