### ISSUE TITLE
vision-camera v3

### ISSUE THREAD

**Issue by tgreco** [tony-xlh/vision-camera-dynamsoft-label-recognizer#2]
Any plans to support v3?

**Comment by xulihang** [comment]
V3 does not have good documentation and examples. The progress is stuck: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/issues/15

**Comment by tgreco** [comment]
@xulihang does this work with v3 yet or whats the plan? 
I can try to put in a PR if you don't plan to make it work.

**Comment by xulihang** [comment]
I will try to adapt the barcode reader plugin first. PRs are welcome.

**Comment by xulihang** [comment]
v1.0.0 is now out with vision camera v3 support.

**Comment by tgreco** [comment]
@xulihang you're a rockstar  🎸
