### ISSUE TITLE
recognize() expects 2 arguments despite documentation.

### ISSUE THREAD

**Issue by sametcl2** [tony-xlh/vision-camera-dynamsoft-label-recognizer#3]
Hi @xulihang,
I'm trying to use this library with `"react-native-vision-camera": "^3.6.8"` and `"vision-camera-dynamsoft-label-recognizer": "^1.0.0"`

In documentation, recognize() function only takes frame but it expects ScanConfig
And I got `Frame Processor threw an error: Exception in HostFunction: java.lang.ArrayIndexOutOfBoundsException: length=0; index=1` error.

**Comment by xulihang** [comment]
This is not the argument's problem. 

You have to add pixelformat="yuv" to the vision camera.

**Comment by sametcl2** [comment]
Thank you @xulihang. This resolved the issue. 
By the way, I looked into your example project. I got an empty object from `recognize()` why might this happen?

**Comment by xulihang** [comment]
If it does not recognize anything, then it returns an empty object. Check out the native code: https://github.com/tony-xlh/vision-camera-dynamsoft-label-recognizer/blob/886ce553d9edeaf867b44909f5adf5a9aa7fe9b8/android/src/main/java/com/visioncameradynamsoftlabelrecognizer/VisionCameraDLRPlugin.java#L29-L64

**Comment by sametcl2** [comment]
Thanks @xulihang, sorry for the late reply. I'm scanning document like the example, why might not recognize anything?
My code like this;

  const scanRegion: ScanRegion = {
    left: 5,
    top: 40,
    width: 90,
    height: 10,
  };

  const updateFrameSize = (width: number, height: number) => {
    if (width !== frameWidth && height !== frameHeight) {
      setFrameWidth(width);
      setFrameHeight(height);
    }
  };

  const updateFrameSizeJS = Worklets.createRunInJsFn(updateFrameSize);

  const frameProcessor = useFrameProcessor(frame => {
    'worklet';
    updateFrameSizeJS(frame.width, frame.height);

    let config: ScanConfig = {};

    config.scanRegion = scanRegion;

    let scanResult = recognize(frame, config);

    console.log(scanResult);
  }, []);

**Comment by xulihang** [comment]
What document are you scanning? Could you upload a sample image?

**Comment by sametcl2** [comment]
I'm trying to scan the bottom white part

<img width="336" alt="Screenshot 2023-12-08 at 18 27 26" src="https://github.com/tony-xlh/vision-camera-dynamsoft-label-recognizer/assets/34509901/b4fd5d64-c901-4b7c-bb11-5bdf387576a4">

**Comment by xulihang** [comment]
You need to put the mrz models and update the runtime setting with the mrz template to recognize it. Check out the example and readme: https://github.com/tony-xlh/vision-camera-dynamsoft-label-recognizer#interfaces

**Comment by sametcl2** [comment]
Thanks a lot @xulihang.

**Comment by xulihang** [comment]
In addition, the default license expires in one day. You need to apply for a trial license.
