### ISSUE TITLE
Frame Not detecting the labels 

### ISSUE THREAD

**Issue by Soban71** [tony-xlh/vision-camera-dynamsoft-label-recognizer#5]
@xulihang @tony-xlh
What is the issue can you tell please as it is not recongizing text label
code:
import React, {useEffect, useState} from 'react';
import {View, Text, StyleSheet} from 'react-native';
import {
useCameraPermission,
useMicrophonePermission,
useCameraDevice,
Camera,
useFrameProcessor,
runAtTargetFps,
useCameraFormat
} from 'react-native-vision-camera';
import { recognize, ScanConfig, ScanRegion, DLRCharacherResult, DLRLineResult, DLRResult } from 'vision-camera-dynamsoft-label-recognizer';

import { Worklets, useSharedValue } from 'react-native-worklets-core';

const App = () => {

const [frameWidth, setFrameWidth] = React.useState(1280);
const [frameHeight, setFrameHeight] = React.useState(720);

const {
hasPermission: cameraPermission,requestPermission: requestCameraPermission} = useCameraPermission();
const {
hasPermission: microphonePermission, requestPermission: requestMicrophonePermission,} = useMicrophonePermission();
const cameraDevice = useCameraDevice('back');
const [loading, setLoading] = useState(true);

useEffect(() => {
if (!cameraPermission) {
requestCameraPermission();
}
if (!microphonePermission) {
requestMicrophonePermission();
}
}, [cameraPermission, microphonePermission]);

useEffect(() => {
if (cameraPermission && microphonePermission) {
setLoading(false);
}
}, [cameraPermission, microphonePermission]);

const format = useCameraFormat(cameraDevice, [
{ videoResolution: { width: 1280, height: 720 } },
{ fps: 10 }
])

const scanRegion:ScanRegion = {
left: 0,
top: 0,
width: 100,
height: 100
}

const updateFrameSize = (width:number, height:number) => {
if (width != frameWidth && height!= frameHeight) {
setFrameWidth(width);
setFrameHeight(height);
}
}

const updateFrameSizeJS = Worklets.createRunInJsFn(updateFrameSize);

const frameProcessor = useFrameProcessor((frame) => {
'worklet';

Explain
runAtTargetFps(1, () => {
  'worklet'
  updateFrameSizeJS(frame.width, frame.height);

  let config:ScanConfig = {};

  console.log("frame width:"+frame.width);
  console.log("frame height:"+frame.height);
  config.scanRegion = scanRegion;
  config.includeImageBase64 = true;
  let scanResult = recognize(frame,config);

  let results:DLRResult[] = scanResult.results;
  let lineResults:DLRLineResult[] = [];
  for (let index = 0; index < results.length; index++) {
    const result = results[index];
    const lines = result?.lineResults;
    if (lines) {
      lines.forEach(line => {
        lineResults.push(line);
      });
    }
  }
  console.log('result is ',results);

})
}, []);
return (

{loading ? (
Loading...
) : !cameraPermission || !microphonePermission ? (

Please grant camera and microphone permissions to use the app.

) : !cameraDevice ? (
No camera device available.
) : (
<Camera

    frameProcessor={frameProcessor}
    format={format}
    pixelFormat='yuv'
    style={styles.camera} device={cameraDevice} isActive={true} />
  )}
</View>
);
};

const styles = StyleSheet.create({
container: {
flex: 1,
justifyContent: 'center',
alignItems: 'center',
},
text: {
fontSize: 24,
fontWeight: 'bold',
textAlign: 'center',
},
camera: {
flex: 1,
width: '100%',
},
});

export default App;

and this output
LOG frame width:1920
LOG frame height:1080
LOG {}

**Comment by xulihang** [comment]
Are you using this in a new project?

Please check if the MRZ model is loaded and the license is correct.
