### ISSUE TITLE
Not working with vision camera v4

### ISSUE THREAD

**Issue by Vadko** [tony-xlh/vision-camera-dynamsoft-label-recognizer#6]
I've installed library within my own project and there were 2 issues on ios (not tested android):
1. Library doesn't recognize mrz labels
2. App crashes in debug mode when trying to read data from MRZ because of memory leak

Then I've tried to clone example repo and result was the same. I assume that something is wrong with library specifically for v4, because v3 example worked perfectly in my case.

**Comment by tony-xlh** [comment]
I think this is related to two issues in v4:

1. The overlay is not accurate. You have to use skia to draw the camera preview: https://github.com/mrousavy/react-native-vision-camera/issues/3231
2. `runAsync` has a memory problem: https://github.com/mrousavy/react-native-vision-camera/issues/3202


You can try this demo to see if the cropped image is correct: https://github.com/tony-xlh/react-native-id-card-scanner

**Comment by Vadko** [comment]
Thanks for sharing this example - it works perfectly fine. However, when trying to put it together with document-normalizer plugin you created - it doesnt work because of DynamsoftCore version difference. Is it something that could be changed?

**Comment by xulihang** [comment]
I have to update the label recognizer plugin to make it compatibile with the document normalizer plugin.

**Comment by xulihang** [comment]
I've updated the two plugins to make them work together.

**Comment by Vadko** [comment]
many thanks for your update. are there any plans for new architecture?

**Comment by xulihang** [comment]
The new capture vision architecture is actually used under the hood. It's just the interface exposed is still the old.

The new react native package uses the new architecture: https://www.npmjs.com/package/dynamsoft-capture-vision-react-native/v/2.4.2000-alpha.3

**Comment by Vadko** [comment]
just tried latest label-recognizer - how are models supposed to be used now if `useCustomModel` was removed?🤔

**Comment by xulihang** [comment]
The MRZ model is now included by default.
